### ISSUE TITLE
Hamburger button appears on non-mobile screens but does nothing

### ISSUE THREAD

**Issue by tofumatt** [mozbrick/mozbrick.github.io#5]
The nav is hidden based on screen size, which is awesome, but the hamburger button that hides/shows it doesn't disappear as well, when it probably should.

I wasn't sure where to file this, so I'm just putting it here, apologies if it's the wrong place.

**Comment by potch** [comment]
This is now fixed!

**Comment by tofumatt** [comment]
:heart:
